[2019-11-25 16:20:13,940][uWSGIWorker1Core0:140377544300608][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api2/api/articleList/]
Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 726, in render
    ret = template.render(context, request=renderer_context['request'])
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 96, in optional_login
    login_url = reverse('rest_framework:login')
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/urls/base.py", line 58, in reverse
    app_list = resolver.app_dict[ns]
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 513, in app_dict
    self._populate()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 464, in _populate
    url_pattern._populate()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 447, in _populate
    for url_pattern in reversed(self.url_patterns):
TypeError: 'set' object is not reversible
[2019-11-25 16:33:24,803][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][WARNING][Not Found: /api2/api/adsa]
[2019-11-25 16:33:28,563][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][WARNING][Not Found: /api2/api/]
[2019-11-25 16:33:37,064][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][WARNING][Not Found: /api2/api/articleLis2]
[2019-11-25 16:34:13,177][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api2/admin/login/]
Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 399, in login
    return LoginView.as_view(**defaults)(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 90, in form_valid
    auth_login(self.request, form.get_user())
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 108, in login
    request.session.cycle_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 297, in cycle_key
    self.create()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 51, in create
    self._session_key = self._get_new_session_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 152, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 47, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")
[2019-11-25 16:34:19,737][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api2/admin/login/]
Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 399, in login
    return LoginView.as_view(**defaults)(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 90, in form_valid
    auth_login(self.request, form.get_user())
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 108, in login
    request.session.cycle_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 297, in cycle_key
    self.create()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 51, in create
    self._session_key = self._get_new_session_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 152, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 47, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")
[2019-11-25 16:34:58,240][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api2/admin/login/]
Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 399, in login
    return LoginView.as_view(**defaults)(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 90, in form_valid
    auth_login(self.request, form.get_user())
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 108, in login
    request.session.cycle_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 297, in cycle_key
    self.create()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 51, in create
    self._session_key = self._get_new_session_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 152, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 47, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")
[2019-11-25 16:38:55,924][uWSGIWorker1Core0:140056096737344][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api2/admin/login/]
Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 399, in login
    return LoginView.as_view(**defaults)(request)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/views.py", line 90, in form_valid
    auth_login(self.request, form.get_user())
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 108, in login
    request.session.cycle_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 297, in cycle_key
    self.create()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 51, in create
    self._session_key = self._get_new_session_key()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 152, in _get_new_session_key
    if not self.exists(session_key):
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 47, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/query.py", line 766, in exists
    return self.query.has_results(using=self.db)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 522, in has_results
    return compiler.has_results()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1070, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/root/site/xiao2Blog/server/venv/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'blog2.django_session' doesn't exist")
[2019-11-26 21:26:10,800][MainThread:4689456576][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:27:45,384][MainThread:4670967232][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:28:27,028][MainThread:4727266752][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:29:01,940][MainThread:4727266752][task_id:django.utils.autoreload][autoreload.py:217][INFO][/Users/liuxiaoer/Desktop/Coder/xiao2Blog/server/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py changed, reloading.]
[2019-11-26 21:29:02,809][MainThread:4579716544][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:29:09,992][MainThread:4732272064][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:31:59,593][MainThread:4472143296][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:39:55,828][MainThread:4559322560][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:40:33,475][Thread-2:123145346969600][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:40:33,476][Thread-1:123145341714432][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:40:33,478][Thread-3:123145352224768][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:40:33,480][Thread-4:123145357479936][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:40:33,548][Thread-4:123145357479936][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:40:33,550][Thread-3:123145352224768][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:40:33,552][Thread-1:123145341714432][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:40:33,553][Thread-2:123145346969600][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:40:33,556][Thread-5:123145362735104][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:40:33,558][Thread-6:123145367990272][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:40:33,770][Thread-6:123145367990272][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:40:33,780][Thread-6:123145367990272][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:40:33,787][Thread-6:123145367990272][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:40:33,791][Thread-6:123145367990272][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:43:30,304][MainThread:4559322560][task_id:django.utils.autoreload][autoreload.py:217][INFO][/Users/liuxiaoer/Desktop/Coder/xiao2Blog/server/server/settings.py changed, reloading.]
[2019-11-26 21:46:31,278][MainThread:4556201408][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:46:33,777][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:46:33,782][Thread-2:123145375260672][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:46:33,786][Thread-3:123145380515840][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:46:33,790][Thread-4:123145385771008][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:46:33,868][Thread-4:123145385771008][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:46:33,870][Thread-2:123145375260672][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:46:33,870][Thread-3:123145380515840][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:46:33,872][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:46:33,874][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:46:33,877][Thread-6:123145396281344][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:46:34,024][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:46:34,031][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:46:35,181][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:46:35,183][Thread-3:123145380515840][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:46:35,185][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:46:35,187][Thread-6:123145396281344][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:46:35,305][Thread-3:123145380515840][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:46:35,307][Thread-6:123145396281344][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:46:35,308][Thread-1:123145370005504][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:46:35,309][Thread-2:123145375260672][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:46:35,310][Thread-4:123145385771008][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:46:35,312][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:46:35,401][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:46:35,406][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:46:35,411][Thread-5:123145391026176][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:47:29,438][MainThread:4556201408][task_id:django.utils.autoreload][autoreload.py:217][INFO][/Users/liuxiaoer/Desktop/Coder/xiao2Blog/server/server/settings.py changed, reloading.]
[2019-11-26 21:47:30,097][MainThread:4536049088][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:47:31,053][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:47:31,056][Thread-4:123145342930944][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:47:31,057][Thread-2:123145332420608][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:47:31,059][Thread-3:123145337675776][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:47:31,176][Thread-3:123145337675776][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:47:31,178][Thread-4:123145342930944][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:47:31,180][Thread-2:123145332420608][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:47:31,182][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:47:31,185][Thread-5:123145348186112][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:47:31,187][Thread-6:123145353441280][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:47:31,373][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:47:31,381][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:47:31,391][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:47:31,407][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:47:31,420][Thread-1:123145327165440][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:47:41,270][MainThread:4625321408][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:48:17,218][Thread-1:123145410285568][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:48:17,222][Thread-2:123145415540736][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:48:17,227][Thread-3:123145420795904][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:48:17,238][Thread-4:123145426051072][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:48:17,399][Thread-4:123145426051072][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:48:17,402][Thread-3:123145420795904][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:48:17,404][Thread-2:123145415540736][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:48:17,406][Thread-1:123145410285568][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:48:17,408][Thread-5:123145431306240][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:48:17,412][Thread-6:123145436561408][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:48:17,513][Thread-5:123145431306240][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:49:03,210][Thread-5:123145431306240][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:49:03,212][Thread-6:123145436561408][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:49:03,219][Thread-1:123145410285568][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/prettify.css]
[2019-11-26 21:49:03,222][Thread-3:123145420795904][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/css/default.css]
[2019-11-26 21:49:03,469][Thread-3:123145420795904][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:49:03,471][Thread-1:123145410285568][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/ajax-form.js]
[2019-11-26 21:49:03,472][Thread-6:123145436561408][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/csrf.js]
[2019-11-26 21:49:03,473][Thread-5:123145431306240][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:49:03,474][Thread-2:123145415540736][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/prettify-min.js]
[2019-11-26 21:49:03,475][Thread-4:123145426051072][task_id:django.request][log.py:228][WARNING][Not Found: /static2/rest_framework/js/default.js]
[2019-11-26 21:49:42,474][MainThread:4625321408][task_id:django.utils.autoreload][autoreload.py:217][INFO][/Users/liuxiaoer/Desktop/Coder/xiao2Blog/server/server/settings.py changed, reloading.]
[2019-11-26 21:49:43,171][MainThread:4361997760][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 21:49:45,634][Thread-1:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/css/bootstrap.min.css]
[2019-11-26 21:49:45,635][Thread-2:123145509363712][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/css/prettify.css]
[2019-11-26 21:49:45,637][Thread-4:123145519874048][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/css/default.css]
[2019-11-26 21:49:45,638][Thread-3:123145514618880][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/css/bootstrap-tweaks.css]
[2019-11-26 21:49:45,677][Thread-4:123145519874048][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/jquery-3.4.1.min.js]
[2019-11-26 21:49:45,689][Thread-1:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/ajax-form.js]
[2019-11-26 21:49:45,692][Thread-3:123145514618880][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/csrf.js]
[2019-11-26 21:49:45,692][Thread-2:123145509363712][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/prettify-min.js]
[2019-11-26 21:49:45,696][Thread-5:123145525129216][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:49:45,703][Thread-6:123145530384384][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/default.js]
[2019-11-26 21:49:45,903][Thread-6:123145530384384][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/csrf.js]
[2019-11-26 21:49:45,913][Thread-6:123145530384384][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/bootstrap.min.js]
[2019-11-26 21:49:45,920][Thread-6:123145530384384][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/prettify-min.js]
[2019-11-26 21:49:45,927][Thread-6:123145530384384][task_id:django.request][log.py:228][WARNING][Not Found: /static/rest_framework/js/default.js]
[2019-11-26 22:18:15,755][Thread-8:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /api/articleCount]
[2019-11-26 22:18:15,817][Thread-8:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /api/articleList]
[2019-11-26 22:18:18,215][Thread-8:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /api/articleCount]
[2019-11-26 22:18:18,460][Thread-8:123145504108544][task_id:django.request][log.py:228][WARNING][Not Found: /api/articleList]
[2019-11-26 22:18:31,268][MainThread:4707597760][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2019-11-26 22:26:38,912][MainThread:4707597760][task_id:django.utils.autoreload][autoreload.py:217][INFO][/Users/liuxiaoer/Desktop/Coder/xiao2Blog/server/blog/views.py changed, reloading.]
[2019-11-26 22:26:39,745][MainThread:4531285440][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
